version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_URL_FONTEND=http://localhost
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_API_AUTH=http://localhost:5001
      - REACT_APP_API_PRODUCT=http://localhost:5002
      - REACT_APP_API_MERCH=http://localhost:5003
      - REACT_APP_API_ORDER=http://localhost:5004
      - REACT_APP_API_CART=http://localhost:5005
      - REACT_APP_API_CHATBOT=http://localhost:5006
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: ./server/api-gateway
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
      - PORT=5000
      - CLIENT_URL=http://localhost
    depends_on:
      - auth-service
      - product-service
      - cart-service
      - order-service
      - merch-service
      - chatbot-service

  auth-service:
    build:
      context: ./server/services/auth-service
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    environment:
      - PORT=5001
      - MONGO_URI=mongodb+srv://coffeedb:_aecc%23KTTKPM@coffeeshop.eo6bc.mongodb.net/coffeeshopdb?retryWrites=true&w=majority&appName=CoffeeShop
      - KEY_SECRET=a7d9f2b8c6e3d1a4f5b7c9e6d2a8f3b4
      - JWT_SECRET=24926e4536bec76a9b996cccf13caff461b96f7eeab756d95a7c51dedc8e8b8e419acaad1498aa6709e82eaa5f25e15e9b45e8ca3da34aa304062aaee128593ebb0083cda148c19937ad42245598c038762a8c7082e111343ba582a391703b63fc4933637d9a4fab937a087e96487a11326b300429691a18037c89ac30474188f207567bbf9cf5afd74f5c8c4ce46b2fd2d8a4c5c432e22d36ffa8da508fbcf5df7572bc77ef12294d321ebc651163f10088f381f8b35fcd74bdb9ab51952bf1ba57ba3f18cf9ae39d4fac93d859ccb60ff09e9fbd765370f8edb0b37143cd536bd89bc3135dabbe364586b98f5e47d6812bc2aeb4cce7765575419ba3ee5ed1
      - AUTH_EMAIL=phantronghau.dev@gmail.com
      - AUTH_PASS=tqdr twza uwnm xcoe

  product-service:
    build:
      context: ./server/services/product-service
      dockerfile: Dockerfile
    ports:
      - '5002:5002'
    environment:
      - PORT=5002
      - MONGO_URI=mongodb+srv://coffeedb:_aecc%23KTTKPM@coffeeshop.eo6bc.mongodb.net/coffeeshopdb?retryWrites=true&w=majority&appName=CoffeeShop
      - KEY_SECRET=a7d9f2b8c6e3d1a4f5b7c9e6d2a8f3b4
      - CLOUDINARY_NAME=ok-but-first-coffee
      - CLOUDINARY_API_KEY=879399268965881
      - CLOUDINARY_API_SECRET=lvEWLW73LskQGLrSPu3EY74ivIQ

  cart-service:
    build:
      context: ./server/services/cart-service
      dockerfile: Dockerfile
    ports:
      - '5005:5005'
    environment:
      - PORT=5005
      - MONGO_URI=mongodb+srv://coffeedb:_aecc%23KTTKPM@coffeeshop.eo6bc.mongodb.net/coffeeshopdb?retryWrites=true&w=majority&appName=CoffeeShop

  order-service:
    build:
      context: ./server/services/order-service
      dockerfile: Dockerfile
    ports:
      - '5004:5004'
    environment:
      - PORT=5004
      - MONGO_URI=mongodb+srv://coffeedb:_aecc%23KTTKPM@coffeeshop.eo6bc.mongodb.net/coffeeshopdb?retryWrites=true&w=majority&appName=CoffeeShop

  merch-service:
    build:
      context: ./server/services/merch-service
      dockerfile: Dockerfile
    ports:
      - '5003:5003'
    environment:
      - PORT=5003
      - MONGO_URI=mongodb+srv://coffeedb:_aecc%23KTTKPM@coffeeshop.eo6bc.mongodb.net/coffeeshopdb?retryWrites=true&w=majority&appName=CoffeeShop

  chatbot-service:
    build:
      context: ./server/services/chatbot-service
      dockerfile: Dockerfile
    ports:
      - '5006:5006'
    environment:
      - PORT=5006
      - MONGO_URI=mongodb+srv://coffeedb:_aecc%23KTTKPM@coffeeshop.eo6bc.mongodb.net/coffeeshopdb?retryWrites=true&w=majority&appName=CoffeeShop
